[package]
name = "raft-distributed-log"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.11"
object-pool = "0.6.0"
prost = "0.14.4"
serf = "0.5.2"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tokio-util = "0.7.19"
tonic = "0.14.6"
tonic-prost = "0.14.6"

[build-dependencies]
tonic-prost-build = "*"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[dev-dependencies]
pretty_assertions = "1.4.1"
